### PR TITLE
Merge in addition by fishycat on the forums, replace migration script

### PR DESCRIPTION
**Pull request by TheBrain0110**
So it turns out after much experimenting with migration scripts, they exist mostly in their own isolated environment. This means they can't do anything with our `global.` table, which is the only thing I wanted it to do (To define `walltier` and `regenrate`, and call `update_walls()`).

Coupled with the fact that the `on_load` handler can't access the `game.` object, and can read but not modify the `global.` table, it means existing wall entities from 0.6.x won't automatically get replaced by their appropriate tiers when updating to 0.7.0. But everything will be set correctly as soon as the next hybrid-upgrade research is completed.

I also incorporated the changes fishycat posted on the forums as "0.6.4" for water patch graphics and descriptions. See https://forums.factorio.com/viewtopic.php?f=93&t=12840&start=60#p361128

### CODE REVIEW

**Comment by TheBrain0110** [comment]
I forgot to really point it out in the commit notes, but another important change is separating the `on_init` and `on_load` events to separate functions that do different things.

~~I also noticed that in the `load` function, it should be `if global.alienregenrate == nil or global.alienregenrate == 0 then regenrate = HybridRegen` from the variables, not `=2`.
Not a biggie, but I like to be consistent, and that shouldn't be a hardcoded value. Just missed it.~~
See next commit, fixed.

And then of course there's the changes to how the research event works, with the new `update_current_tier()` function. But that's pretty obvious and self-explanatory just by looking at the diffs. Just a bit of refactoring to keep things tidy.

**Comment by TheBrain0110** [comment]
Oh neat. Pushing to my repo automatically adds the new commits to the pull request.

**Review by vedrit — APPROVED** [review]
Looks good. Thanks for you help!

**Comment by TheBrain0110** [comment]
Any chance of it getting posted to the mod portal for public download soon?
See also [your forum thread](https://forums.factorio.com/viewtopic.php?f=190&t=12840&p=361359#p361359)

**Comment by vedrit** [comment]
Apparently I missed some changes. I'm just reviewing them then I'll get it all committed and post the updated version

**Review by vedrit — APPROVED** [review]
Looks good. Thanks again!

**Pull request merged**
